- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/util/Parser.java
I think filtering guilds by members size can be useful on small servers to prevent rank farming by one-person guilds in top ranking.
> Minimal member check in ranking's top system.

- src/main/java/net/dzikoysk/funnyguilds/basic/util/RegionUtils.java
RegionUtils.isNear zawsze zwracał false jak jest więcej niż dwie gildie
> Fix RegionUtils.isNear

- src/main/java/net/dzikoysk/funnyguilds/basic/OfflineUser.java
- src/main/java/net/dzikoysk/funnyguilds/basic/util/RankSystem.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
- src/main/java/net/dzikoysk/funnyguilds/util/NotePitch.java
- src/main/java/net/dzikoysk/funnyguilds/util/elo/EloUtils.java
**1.** Usunięcie metody setBanned() z klasy OfflineUser z powodu braku metody setBanned() w klasie OfflinePlayer na wersji 1.12 (metoda i tak była nieużywana)
**2.** Dodanie enumu RankSystem i ustanowienie trzech systemów rankingu - ELO, procentowego i statycznego
**3.** Dodanie do configu zmiennej z czasem, który musi upłynąć od walki, aby znowu naliczało ranking
**4.** Poprawienie klasy NotePitch, aby była kompatybilna ze wszystkimi wersjami MC od 1.8 w górę
**5.** Zmiany w configu - usunięcie _Tribute_ z nazwy, dodanie informacji o możliwości podania metadaty do itemu
Ze względu na wcześniejszy błąd w rankingu ELO i dzisiejsze zmiany - jestem za jak najszybszym wydaniem nowego release
> Rank fixes and changes

- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/util/Version.java
Tak naprawdę jest to scalenie #693 i #694 z przerobieniem nazewnictwa sekcji w configu, aby pasowała do reszty i z poprawieniem warunku sprawdzającego permission i stan włączenia informacji o aktualizacji, aby faktycznie działał jak należy
Dzięki @RabbitTheDEV za poddanie pomysłu na zmiany, ale szybciej będzie jeśli po prostu sam zrobię obie te zmiany w jednym PR :)
> Add update info toggle

- src/main/java/net/dzikoysk/funnyguilds/element/gui/GuiActionHandler.java
setCancelled(true) calls setResult(DENY) that is already invoced above.
[LINK](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/event/inventory/InventoryInteractEvent.java#77)
> Remove setCancelled method invocation.

- pom.xml
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
**Fixing default bugged-blocks-exclude configuration by adjusting it with the following:**
- Prevent using tnt minecarts by placing rails
- Prevent moving/removing blocks from other guilds using pistons
- Prevent using all other blocks that may produce redstone output to prevent further exploits
**Reasons and motivation:**
It is expected from this functionality to allow escapes from terrain of enemy guilds that cannot be escaped normally (artificial pits in terrain), not to allow full bypass of region protection.
> Make bugged blocks less bugged

- src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockPlace.java
- src/main/java/net/dzikoysk/funnyguilds/util/nms/Reflections.java
While being popularized in the guilds community, current implementation was unusable with other plugins (especially with plugins modifying terrain around after block place). This PR changes completely how bugged blocks function works under the hood.
It has some drawbacks, but I believe it is overall better and more fun for users. Players can just hold a right click after first jump to build a tower and combined with clicking the space bar it can be even faster towering method, which enables more skill based gameplay during guild wars.
> Stop bugged blocks from breaking in some way almost all plugins executing actions after BlockPlaceEvent

- src/main/java/net/dzikoysk/funnyguilds/hook/PlaceholderAPIHook.java
Fixes PlaceholderAPI error - FunnyGuilds gets disabled first, so getting the plugin version from it becomes impossible
> Fix error on PlaceholderAPI disabling

- src/main/java/net/dzikoysk/funnyguilds/listener/TntProtection.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/EntityExplode.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/SpaceUtils.java
Previously, we've been handling explosion event improperly, because we've not been taking into an account the fact that other plugins (for example WorldGuard) often doesn't cancel the event, but instead they are clearing the list of the blocks that have been affected by the explosion and because of that our custom block explosion logic could be fired even if it shouldn't be.
Now, we're calculating all the blocks that we need for our purposes before most of the protection (but not only) plugins code is fired and modifying the explosion event block list so that blocks that we're interested in are included, then let other plugins run their event handlers, and then based on the resulting event data we can handle explosion event properly without breaking interaction with other plugins.
Closes …
> Fix interaction between our plugin and others while handling explosion event

- src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockBreak.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockIgnite.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockPlace.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/BucketAction.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/EntityPlace.java
- src/main/java/net/dzikoysk/funnyguilds/system/protection/ProtectionSystem.java
This allows other plugins to check if blocks are protected without spamming the player with regionOther message.
> Get the regionOther message out of the util class

- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
Poprawiłem kilka literówek (`gildi` -> `gildii` https://pl.wiktionary.org/wiki/gildia ), oraz ograniczyłem nadużywane wtrącenia w zdaniach za pomocą nawiasów. Widziałem na discordzie kilka razy, że przez wtrącanie np pustych list jako sugestii wyłączenia jakiejś opcji, tworzyły się następujące ciągi znaków w komentarzach konfiguracji: `[])`. Osoby nieobyte z programowaniem pewnie nawet nie rozumieją co oznacza `[]`, więc szybko zaznaczają i kopiują razem z zamykającym nawiasem. Kropki lub przecinki mogą być dla nich znacznie bardziej oczywistymi elementami symbolizującymi, że już nie jest to część tego, co powinni przekleić.
> Make configs more readable

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/FunnyGuildsLogger.java
At the moment the plugin is hiding the real error cause of some issues, this PR fixes it by making sure the full stacktrace is visible.
> Enhance startup errors, make FunnyGuildsLogger print full stacktrace instead of first part

- src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/MaterialUtils.java
- added missing space after `if` keyword
- else is redundant 
- although it is checked if hasMetaItem(); The IDE can't see it, so I changed it to null check
> a small improvement in the appearance of the code

- src/main/java/net/dzikoysk/funnyguilds/basic/guild/Guild.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/ProtectionCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/user/CreateCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/user/InfoCommand.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/MessageConfiguration.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseGuild.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
- src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatGuild.java
- src/main/java/net/dzikoysk/funnyguilds/data/util/DeserializationUtils.java
- src/main/java/net/dzikoysk/funnyguilds/system/war/WarSystem.java
Linked: https://github.com/FunnyGuilds/FunnyGuilds/issues/1487
System ochrony został uproszczony, aby był on bardziej zależny od administratora. Administrator może ustawić dowolną datę wygaśnięcia ochrony gildii nie zależnie od tego, czy gildia posiada już swoją ochronę, inaczej mówiąc, jest w stanie skrócić ochronę.
> Simple protection time system rework.

- src/main/java/net/dzikoysk/funnyguilds/basic/user/UserCache.java
Linked: https://github.com/FunnyGuilds/FunnyGuilds/issues/1559
Wydaje mi się, że to rozwiąże problem. Widzę, że często pojawia się sytuacja, gdzie cache jest czyszczone (chyba z 9x), przez co istnieją pewne wyjątki, w których już nie ma gracza atakującego w cache.
> GH-1559 Add "not contains key" check

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
Last okaeri-configs [update](https://github.com/FunnyGuilds/FunnyGuilds/commit/21a8566d31f9674b64198e4af4aa4ea0e23c79ed) provides Names annotation inheritance (for inner classes) which leads to the difference in eg. the mysql section. This PR addresses that issue, also removing unnecessary CustomKey annotations.
> Fix config names inconsistency

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/basic/user/User.java
- src/main/java/net/dzikoysk/funnyguilds/basic/user/UserManager.java
- src/main/java/net/dzikoysk/funnyguilds/basic/user/UserUtils.java
- src/main/java/net/dzikoysk/funnyguilds/command/user/InfoCommand.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseGuild.java
- src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatGuild.java
- src/main/java/net/dzikoysk/funnyguilds/element/tablist/variable/DefaultTablistVariables.java
PR ma zmienić system przetrzymywania userów (Od teraz są przetrzymywani w instancji klasy UserManager). Wszystkie wcześniejsze metody w klasie User i UserUtils zostały oznaczone adnotacją `@Deprecated` i dodatkowo opisane, jakich metod powinno się używać w zastępstwie.
Np.:
Wiem, że w FG nie robimy dokumentacji. Jeśli to możliwe fajnie jakby była ona dostępna na czas istnienia tych metod.
> Simple rework of user system.

- plugin/build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/basic/guild/Guild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/command/user/BaseCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/command/user/CreateCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/command/user/ValidityCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/FunnybinRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseGuild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatGuild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/element/notification/bossbar/provider/BossBarProvider.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/system/war/WarSystem.java
- replaces duration fields with the [proper Duration type](https://github.com/OkaeriPoland/okaeri-configs/blob/master/serdes-commons/src/main/java/eu/okaeri/configs/serdes/commons/duration/DurationTransformer.java)
- adapts codebase to the new fields
- removes next chunk of dirty parsing in the load method
- enhances config with more validation annotations
- updates `okaeri-configs` to `3.1.0`
Fully compatible with minor exceptions: some fields with weird values like "-123123" as duration may not pass new validation and would require manual change to meet current standard. Most users should not be affected.
Third party changes from `okaeri-configs` do not affect current code base, but may affect other plugins accessing FunnyGuild's configuration directly. This is also true for field …
> Enhance config with Duration instead of inconsistent long representations

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/prefix/IndividualPrefix.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/prefix/IndividualPrefixManager.java
Mały cleanup klasy IndividualPrefix.
`IndividualPrefix#replace(String f, String r, String t)` -> `IndividualPrefix#preparePrefix(String text, Guild guild)`
Zostały usunięte null checki, które zakładają np. że members może mieć null'a w kolekcji, `user.getName()` lub `guild.getTag()` zwraca null. Jeśli wystąpi taki przyapdek to raczej nie jest problem individualprefixów, tylko np. źle działającej bazy danych.
> Cleanup IndividualPrefix and remove useless null checks.

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookManager.java
- plugin/src/main/resources/plugin.yml
Because of no softdepend - HolographicDisplays could be enabled after FG, and if it encountered an error - HD could disable itself, but FG would still use the initialized hook. Now - all hook plugins need to be fully enabled before trying to hook into them.
> Correct HolographicDisplays hook

- plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatGuild.java
If an empty Set was loaded from .yml guild file - the `loadSet()` method returned a null. However the `findByNames()` method assumed that the given Set parameter is not null.
Example guild file: https://pastebin.com/PfgUQFmT
Example error: https://pastebin.com/1zA2zWDU
> Fix possible iteration on null Set

- plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatGuild.java
On MC version 1.18 - current set syntax of the flat data files is not being loaded correctly (it results in an empty MemorySection object):
```yaml
members: !!set
Kamilkime: null
Kimek: null
```
I suggest changing such data saves to a List format:
```yaml
members:
- Kimek
- Kamilkime
```
Current data on older MC versions will be seamlessly transformed, while data on MC 1.18 will actually start working correctly.
> Change collection save format for YAML data model

- nms/v1_10R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_10R1/playerlist/V1_10R1PlayerList.java
- nms/v1_11R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_11R1/playerlist/V1_11R1PlayerList.java
- nms/v1_12R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_12R1/playerlist/V1_12R1PlayerList.java
- nms/v1_13R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_13R2/playerlist/V1_13R2PlayerList.java
- nms/v1_14R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_14R1/playerlist/V1_14R1PlayerList.java
- nms/v1_15R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_15R1/playerlist/V1_15R1PlayerList.java
- nms/v1_16R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_16R3/playerlist/V1_16R3PlayerList.java
- nms/v1_17R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_17R1/playerlist/V1_17R1PlayerList.java
- nms/v1_18R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R1/playerlist/V1_18R1PlayerList.java
- nms/v1_8R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_8R3/playerlist/V1_8R3PlayerList.java
- nms/v1_9R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_9R2/playerlist/V1_9R2PlayerList.java
Before migration to modules, player list implementation wouldn't send
header and footer if they were an empty strings.
Current behavior causes flickering when there is something else on the
server that is sending header/footer packets and our player list is in use.
Thus, send player list header and footer only if they are defined to be empty
to prevent this issue from occurring.
> Do not send player list header and footer if they are both empty

- plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseGuild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatGuild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserUtils.java
Fix error thrown when trying to get a value from region option, despite regions being disabled:
```
[18:12:20] [Server thread/INFO]: [FunnyGuilds] Regions are disabled and thus - not loaded
[18:12:20] [Server thread/ERROR]: [FunnyGuilds] 
[18:12:20] [Server thread/ERROR]: [FunnyGuilds] Could not load data from database
[18:12:20] [Server thread/ERROR]: [FunnyGuilds] 
[18:12:20] [Server thread/ERROR]: [FunnyGuilds] java.util.NoSuchElementException: Value is not defined
[18:12:20] [Server thread/ERROR]: [FunnyGuilds]     at panda.std.Option.get(Option.java:228)
[18:12:20] [Server thread/ERROR]: [FunnyGuilds]     at net.dzikoysk.funnyguilds.data.flat.FlatGuild.deserialize(FlatGuild.java:85)
[18:12:20] [Server thread/ERROR]: [FunnyGuilds]     at …
```
> Fix empty region option get, remove deprecated uses of UserUtils

- plugin/build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/ReloadRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/ConfigurationFactory.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0001_Fix_freecam_compensation_key_case.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0002_Migrate_old_heart_configuration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0003_Migrate_old_tnt_protection_configuration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0004_Migrate_tablist_into_separate_file.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0005_Fix_heart_configuration_centery_key.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/T0001_Update_player_list_animated.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/HeartConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistPageSerializer.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/IndividualPlayerList.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
This PR aims to fix partial configuration loss when upgrading from 4.9.7 to 4.10.0 by:
- updating `okaeri-configs` to `4.0.0-beta13` for built-in migrations
- creating `net.dzikoysk.funnyguilds.config.migration` package for further migrations
- `P0002_Migrate_old_heart_configuration: Migrate` old top-level keys to heart-configuration subconfig
- `P0003_Migrate_old_tnt_protection_configuration`: Migrate old top-level keys to tnt-protection subconfig
- `P0004_Migrate_tablist_into_separate_file`: Migrate old config.yml tablist into tablist.yml
- `T0001_Update_player_list_animated`: Preserve behavior of empty tablist pages by updating player-list-animated
- `P0001_Fix_freecam_compensation_key_case`: Rename freeCam-compensation to freecam-compensation
- …
> Add legacy configuration migrations

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/FunnyTime.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/transformer/FunnyTimeTransformer.java
This PR is brought to you by YAML specification. Order your copy now and get 10% off by converting `key: 10:00` into `key: 600`.
> Add fallback FunnyTime parsing as minutes from midnight (Fixes #1603)

- plugin/src/main/resources/plugin.yml
FunnyGuilds loads before the Multiverse-Core, causing guilds on Multiverse worlds to be moved to the default world.
> Add Multiverse-Core as a soft dependency

- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/NmsUtils.java
Gdy nie wykryto odpowiedniego `NmsAccessora` to rzucaliśmy wyjątek przez `FunnyGuildsLogger` - a on... używał tego NmsAccessora do sprawdzania ilości przeładowań serwera więc FunnyGuilds#shutdown nie było nawet callowane 
Dodatkowo został poprawiony exception rzucany userom, aby osoby mniej techniczne były w stanie zrozumieć dlaczego plugin nie działa
> Fix server shutdown

- build.gradle.kts
- nms/api/build.gradle.kts
- nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/ProtocolDependentHelper.java
- nms/v1_10R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_10R1/playerlist/V1_10R1PlayerList.java
- nms/v1_11R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_11R1/playerlist/V1_11R1PlayerList.java
- nms/v1_12R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_12R1/playerlist/V1_12R1PlayerList.java
- nms/v1_13R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_13R2/playerlist/V1_13R2PlayerList.java
- nms/v1_14R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_14R1/playerlist/V1_14R1PlayerList.java
- nms/v1_15R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_15R1/playerlist/V1_15R1PlayerList.java
- nms/v1_16R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_16R3/playerlist/V1_16R3PlayerList.java
- nms/v1_17R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_17R1/playerlist/V1_17R1PlayerList.java
- nms/v1_18R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R2/playerlist/V1_18R2PlayerList.java
- nms/v1_19R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R1/playerlist/V1_19R1PlayerList.java
- nms/v1_19R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R2/playerlist/V1_19R2PlayerList.java
- nms/v1_8R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_8R3/playerlist/V1_8R3PlayerList.java
- nms/v1_9R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_9R2/playerlist/V1_9R2PlayerList.java
In 1.19.3 player list entry sorting got changed and it includes GameProfile name in the sorting process.
To allow players joining with 1.19.3 client on <1.19.3 servers and having proper sorting on the player list, player list now uses proper GameProfile name based on the client's protocol version, retrieved from the ViaVersion's API.
> GH-2276 Mitigate player list entry sorting when using ViaVersion
