FunnyGuilds/FunnyGuilds

- src/main/java/net/dzikoysk/funnyguilds/util/Parser.java
`if (calc) {}` is always `true`
> remove useless condition

- src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java
- src/main/java/net/dzikoysk/funnyguilds/util/reflect/EntityUtil.java
Naprawienie kryształów które znikały po odładowaniu chunka.
> Bugfix crystal

- src/main/java/net/dzikoysk/funnyguilds/basic/util/RegionUtils.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcCreate.java
https://github.com/FunnyGuilds/FunnyGuilds/issues/516 poprawka
> Bugfix guild expand

- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java
- src/main/java/net/dzikoysk/funnyguilds/util/element/tablist/AbstractTablist.java
**1.** Dodanie do configu sekcji _guild-min-members-pos-string_, w której podawany jest String, na który zamieniana jest na TABie zmienna _{G-POSITION}_, gdy gildia ma zbyt mało członków lub gracz nie jest w żadnej gildii (https://github.com/FunnyGuilds/FunnyGuilds/issues/617)
**2.** Poprawienie wysyłania wiadomości przy wejściu gracza na region gildii (https://github.com/FunnyGuilds/FunnyGuilds/issues/618)
> Region enter notification fix + guild position string replacement

- src/main/java/net/dzikoysk/funnyguilds/basic/User.java
- src/main/java/net/dzikoysk/funnyguilds/command/Commands.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/AxcSpy.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/listener/PlayerChat.java
> add /ga spy command

- src/main/java/net/dzikoysk/funnyguilds/command/admin/AxcMain.java
- src/main/java/net/dzikoysk/funnyguilds/listener/PlayerChat.java
> fix message duplication while using /ga spy, add /ga spy to AxcMain

- src/main/java/net/dzikoysk/funnyguilds/basic/Rank.java
- src/main/java/net/dzikoysk/funnyguilds/command/Commands.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcBase.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcEscape.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcInfo.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcPlayer.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/MessagesConfig.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
- src/main/java/net/dzikoysk/funnyguilds/util/element/tablist/AbstractTablist.java
**1.** Dodanie komendy /ucieczka
**2.** Dodanie zmiennej {KDR} do użytku w niektórych miejscach i dodanie metody w klasie _Rank_, która to KDR liczy
> Escape command and KDR

- .travis.yml
- README.md
- pom.xml
Po czasie oczekiwania raczej wątpię, że #673 zostanie rozwiązane.
> Remove code coverage system.

- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockPlace.java
Można byłoby to zrobić w jednym tasku, ale kto by się tym przejmował? ¯\_(ツ)_/¯
> Implement bugged blocks.

- .gitignore
- pom.xml
- src/main/java/net/dzikoysk/funnyguilds/events/guild/CancellableGuildEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/GuildCreateEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/GuildDeleteEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/GuildEnlargeEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/GuildEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/ally/CancellableGuildAllyEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/ally/GuildAcceptAllyInvitationEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/ally/GuildAllyEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/ally/GuildBreakAllyEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/ally/GuildSendAllyInvitationEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/CancellableGuildMemberEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberAcceptInviteEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberDeputyEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberInviteEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberJoinEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberKickEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberLeaderEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/guild/member/GuildMemberLeaveEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/rank/CancellableRankEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/rank/RankChangeByAdminEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/rank/RankChangeEvent.java
- src/main/java/net/dzikoysk/funnyguilds/events/rank/RankEvent.java
Tworzę tego PRa wcześniej, żeby inni mogli na bieżąco obserwować postęp w implementacji #683. Sugeruje też z tamtego issue przenieść dyskusję tutaj.
> [WIP] Custom events.

- src/main/java/net/dzikoysk/funnyguilds/util/NotificationUtil.java
Poprawienie błędu zgłoszonego w #702
> EnumTitleAction fix

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcItems.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/MessagesConfig.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/util/IOUtils.java
- src/main/java/net/dzikoysk/funnyguilds/util/ItemUtils.java
- src/main/java/net/dzikoysk/funnyguilds/util/StringUtils.java
- src/main/java/net/dzikoysk/funnyguilds/util/Version.java
**1.** Teraz można całkowicie wyłączyć updater, również przy uruchamianiu pluginu
**2.** Zostały dodane funkcje zaproponowane w #677
> Dodanie możliwości wyłączenia updatera, więcej konfiguracji GUI

- src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
> Fix in assist system

- src/main/java/net/dzikoysk/funnyguilds/command/ExcCreate.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/MessagesConfig.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
> Implement required experience to create guild

- src/main/java/net/dzikoysk/funnyguilds/util/element/tablist/variable/DefaultTablistVariables.java
https://github.com/FunnyGuilds/FunnyGuilds/issues/810
> Hide vanished players from {ONLINE} tab variable.

- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfig.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/EntityExplode.java
https://github.com/FunnyGuilds/FunnyGuilds/issues/790
> Added configurable temporary TNT protection in guilds

- src/main/java/net/dzikoysk/funnyguilds/basic/Guild.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcInfo.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/MessagesConfig.java
#819
Miałem wątpliwości czy zostawić tą wiadomość "Brak" hardcoded, ale stwierdziłem że skoro klasa TimeUtils robi tak samo to wstępnie zostawię.
> Fixed bug with war-protection and added {GUILD-PROTECTION} variable for /info command

- src/main/java/net/dzikoysk/funnyguilds/util/element/tablist/variable/DefaultTablistVariables.java
W sumie to trochę leczenie objawowe
> Fixed NPE with {ONLINE} variable, possibly fix #825

- src/main/java/net/dzikoysk/funnyguilds/element/NotificationBar.java
Signed-off-by: insertt <inserttdev@gmail.com>
> Lookup method from EntityEnderDragon class without parameter type to preserve compatibility

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/command/ExcFunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/ConfigHelper.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/IOUtils.java
- src/main/java/net/dzikoysk/funnyguilds/util/telemetry/FunnyTelemetry.java
- src/main/java/net/dzikoysk/funnyguilds/util/telemetry/FunnybinResponse.java
> FunnyTelemetry

- pom.xml
Finally after 2 years, 24 days and 52 minutes of adding Hikari to FunnyGuilds, for the first time, we will be able to see its logs =)
> Fix logs (and whitespaces in pom.xml broken by Kamilkime)

- src/main/java/net/dzikoysk/funnyguilds/command/ExcBase.java
- src/main/resources/plugin.yml
> Allow bypassing base items for players with permission

- src/main/java/net/dzikoysk/funnyguilds/element/tablist/AbstractTablist.java
- src/main/java/net/dzikoysk/funnyguilds/element/tablist/impl/v1_10_R1/TablistImpl.java
- src/main/java/net/dzikoysk/funnyguilds/element/tablist/impl/v1_13_R2/TablistImpl.java
- src/main/java/net/dzikoysk/funnyguilds/element/tablist/impl/v1_8_R1/TablistImpl.java
- src/main/java/net/dzikoysk/funnyguilds/element/tablist/impl/v1_8_R3/TablistImpl.java
Introducing significantly less placeholder requests per player. About 25x faster.
> Optimize tablist placeholders

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/basic/guild/GuildUtils.java
- src/main/java/net/dzikoysk/funnyguilds/basic/rank/Rank.java
- src/main/java/net/dzikoysk/funnyguilds/basic/rank/RankManager.java
- src/main/java/net/dzikoysk/funnyguilds/basic/rank/RankRecalculationTask.java
- src/main/java/net/dzikoysk/funnyguilds/basic/rank/RankUtils.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/PermissionUtils.java
This PR remakes ranking system calculations by replacing on-change recalculations to configurable interval recalculations using asynchronous task. This also closes #1183.
> Remake ranking system calculations

- src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
Make code more readable, add a possibility to load data separately
> Make code more readable

- src/main/java/net/dzikoysk/funnyguilds/command/ExcItems.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/ItemUtils.java
> Add possibility to format items name in the GUI.

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
- src/main/java/net/dzikoysk/funnyguilds/listener/BlockFlow.java
https://github.com/FunnyGuilds/FunnyGuilds/issues/1199
> Water and lava flow only for regions

- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
- src/main/java/net/dzikoysk/funnyguilds/element/Dummy.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/ItemUtils.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/bukkit/MaterialUtils.java
- src/main/java/net/dzikoysk/funnyguilds/util/commons/spigot/ItemComponentUtils.java
Add amount Suffix.
Fix bug in Dummy.java
```java
[10:59:51] [Server thread/INFO]: arassscc lost connection: Disconnected
[10:59:51] [Server thread/INFO]:  » WIN Campler (+17) zabil arassscc (-17) uzywajac [diamentowy miecz]
[10:59:51] [pool-11-thread-1/ERROR]: [FunnyGuilds] 
[10:59:51] [pool-11-thread-1/ERROR]: [FunnyGuilds] An error occurred while handling concurrent request
[10:59:51] [pool-11-thread-1/ERROR]: [FunnyGuilds] 
[10:59:51] [pool-11-thread-1/ERROR]: [FunnyGuilds] java.lang.NullPointerException
[10:59:51] [pool-11-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.Dummy.updateScore(Dummy.java:28)
[10:59:51] [pool-11-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.DummyManager.updateScore(DummyManager.java:17)
[10:59:51] …
```
> Add possibility to format and translate the {ITEM} and {ITEMS} tags.

- src/main/java/net/dzikoysk/funnyguilds/element/Dummy.java
> Fix null Player bug in Dummy

- .github/workflows/maven.yml
> GH-1384 Test compilation against JDK8, 11 and 15

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
- src/main/java/net/dzikoysk/funnyguilds/listener/TntProtection.java
- src/main/java/net/dzikoysk/funnyguilds/listener/region/EntityExplode.java
> GH-1437 Support global tnt protection time 

- src/main/java/net/dzikoysk/funnyguilds/command/admin/KickAdminCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/KillsCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/LeaderAdminCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/LivesCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/MainCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/MoveCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/NameCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/PointsCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/ProtectionCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/SpyCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/TagCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/TeleportCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/UnbanCommand.java
- src/main/java/net/dzikoysk/funnyguilds/command/admin/ValidityAdminCommand.java
Implement FunnyCommands in kick, kills, leader, lives, move, name, points, protection, spy, tag, teleport, unban and validity commands.
> GH-1441 Reimplement admin commands using FunnyCommands

- src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseGuild.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseRegion.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/element/SQLBuilderStatement.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/element/SQLUtils.java
> GH-1451 Simplify delete & update database queries

- src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/database/DatabaseUpdateGuildRequest.java
Bug: https://github.com/FunnyGuilds/FunnyGuilds/issues/1466
> GH-1466 Fix database update requests for guilds with disabled regions

- src/main/java/net/dzikoysk/funnyguilds/FunnyGuildsVersion.java
Przed:
Po:
Błąd będzie w console:
```
[21:55:40 WARN]: [FunnyGuilds]
Warning: file_get_contents(https://raw.githubusercontent.com/FunnyGuilds/FunnyGuilds/master/updater.txt): failed to open stream: Operation timed out in /usr/home/dzikoysk/domains/funnyguilds.dzikoysk.net/public_html/latest.php on line 5
Cannot load
```
> Hide error and print in console.

- src/main/java/net/dzikoysk/funnyguilds/basic/guild/Region.java
- src/main/java/net/dzikoysk/funnyguilds/command/user/CreateCommand.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/PluginConfiguration.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
- src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatDataModel.java
- src/main/java/net/dzikoysk/funnyguilds/data/util/DeserializationUtils.java
Also, fix some quirks with the Region class, as having side-effects in the constructor is error-prone.
> GH-225 Properly check distance from the border while creating the guild

- src/main/java/net/dzikoysk/funnyguilds/command/user/CreateCommand.java
- src/main/java/net/dzikoysk/funnyguilds/system/security/SecuritySystem.java
- src/main/java/net/dzikoysk/funnyguilds/util/FunnyBox.java
BoundingBox is not available until 1.13, gotta use FunnyBox instead!
> GH-1502 Use FunnyBox instead of BoundingBox for compatibility with 1.8+

- src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseUser.java
- src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
- src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatDataModel.java
Wydaje mi się, że usuwanie plików nie rozwiąże problemu, który wystąpi podczas ładowania bazy danych, a bardziej go zakryje, przez co odkrycie samego problemu, jak i naprawienie jego źródła potrwa o wiele dłużej.
> remove file removing in database flat & remove redundant variable in database sql

- src/main/java/net/dzikoysk/funnyguilds/command/user/JoinCommand.java
- src/main/java/net/dzikoysk/funnyguilds/data/configs/MessageConfiguration.java
Linked: https://github.com/FunnyGuilds/FunnyGuilds/issues/1543
> Join Command bug fix.

- src/main/java/net/dzikoysk/funnyguilds/basic/rank/RankUtils.java
Linked: https://github.com/FunnyGuilds/FunnyGuilds/issues/1508
> GH-1508 Add color of the war relationship between guilds on the TabList

- src/main/java/net/dzikoysk/funnyguilds/listener/region/EntityProtect.java
Linked: https://github.com/FunnyGuilds/FunnyGuilds/issues/1548
> GH-1547 Fix compatibility with 1.8.8-1.12.2 for a check "instanceof Mob"

- plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseGuild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/DeathsCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/KillsCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/PointsCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/InfoCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/PlayerInfoCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/variable/DefaultTablistVariables.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Guild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/GuildRank.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerQuit.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/Rank.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankRecalculationTask.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankUtils.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/User.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserRank.java
> Small rank system rework

- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/war/WarInfoRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/DeleteAdminCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/BreakCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/InfoCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/Placeholders.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/variable/DefaultTablistVariables.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Guild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerInteract.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankRecalculationTask.java
Potrzebuję jakiegoś normalnego sposobu do używania placeholdersów w hologramach, a  https://github.com/FunnyGuilds/FunnyGuilds/pull/1599 nie rusza z miejsca.
Chcę dodać tę klasę, dopóki https://github.com/FunnyGuilds/FunnyGuilds/pull/1599 nie będzie zrobiony. Później wystarczy ją usunąć i zastąpić czymś z tamtego PR mini mess...
> Add placeholders system.

- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/rank/RankUpdateGuildRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/rank/RankUpdateUserRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/PointsCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/TopCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/LeaderHeadsHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/PluginHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Guild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankRecalculationTask.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankUtils.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserManager.java
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/FunnyGuildsSpec.groovy
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/rank/RankUtilsTest.groovy
Small cleanup - mostly in rank system
> Small cleanup

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/InfoCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/Placeholders.java
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/BukkitSpec.java
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/FunnyGuildsSpec.groovy
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/feature/placeholders/PlaceholdersTest.groovy
> Fix coloring online players and add tests

- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/war/WarInfoRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/DeleteCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/war/WarPacketCallbacks.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/war/WarSystem.java
> GH-1663 Fix displayed time of protection

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockPlace.java
> GH-1370 Add bypass to region protection

- nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/playerlist/PlayerListConstants.java
- nms/v1_10R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_10R1/playerlist/V1_10R1PlayerList.java
- nms/v1_11R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_11R1/playerlist/V1_11R1PlayerList.java
- nms/v1_12R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_12R1/playerlist/V1_12R1PlayerList.java
- nms/v1_13R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_13R2/playerlist/V1_13R2PlayerList.java
- nms/v1_14R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_14R1/playerlist/V1_14R1PlayerList.java
- nms/v1_15R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_15R1/playerlist/V1_15R1PlayerList.java
- nms/v1_16R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_16R3/playerlist/V1_16R3PlayerList.java
- nms/v1_17R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_17R1/playerlist/V1_17R1PlayerList.java
- nms/v1_18R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R1/playerlist/V1_18R1PlayerList.java
- nms/v1_8R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_8R3/playerlist/V1_8R3PlayerList.java
- nms/v1_9R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_9R2/playerlist/V1_9R2PlayerList.java
Empty component created as per protocol suggestions: https://wiki.vg/Protocol#Player_List_Header_And_Footer
> Fix client NPE when header or footer is empty

- .github/dependabot.yml
- build.gradle
- plugin/build.gradle
Z jakiegoś nieznanego powodu zbicie wersji dependency WE do 7.2.6 "naprawia" #1708
> Fix for GH-1708

- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/CreateCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/AbstractPluginHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/BungeeTabListPlusHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/FunnyTabHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/LeaderHeadsHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/MVdWPlaceholderAPIHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/PlaceholderAPIHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/PluginHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/VaultHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/holographicdisplays/HologramUpdateHandler.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/holographicdisplays/HologramUpdateLocationHandler.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/holographicdisplays/HolographicDisplaysHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldedit/WorldEdit6Hook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldedit/WorldEdit7Hook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldedit/WorldEditHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard6Hook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard7Hook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuardHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/IndividualPlayerList.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/variable/DefaultTablistVariables.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/GuildManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/EntityDamage.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/User.java
> GH-1742 Improve plugin hooks system

- plugin/build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/HeartConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/MoveCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/CreateCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Region.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/LocationUtils.java
> GH-1732 Support World#getMinHeight() dla 1.18

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/PlaceholderAPIHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/prefix/IndividualPrefix.java
> GH-1742 Improve hooks

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/war/WarSystem.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Guild.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Region.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/DamageCache.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/User.java
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/FunnyGuildsSpec.groovy
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/shared/bukkit/FunnyBoxTest.groovy
Mostly reorganize methods in classes like User, Guild etc. to be arranges in more meaningful way (I think?) and some other smaller changes.
> More cleanup

- .github/dependabot.yml
- plugin/build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookManager.java
#1708 
Removing WE from dependencies and use transitive WE dependency from WG fix error... finally?
> GH-1708 Another weird fix 

- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java
> Fix unnecessary creating task on mouse movement

- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/BucketAction.java
> GH-1706 Add ability to fill and pour buckets on guild regions

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/MessageConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/HologramConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/Placeholders.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/variable/DefaultTablistVariables.java
Resolves #1773
Ready to review and merge
> GH-1773 Implement LIVES-SYMBOL with repeating symbol instead of numbers

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/RankUtils.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/User.java
> GH-1480 Implement some vanish plugins support

- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/DataModel.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/SQLDataModel.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/DeleteAdminCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/ConfirmCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/validity/GuildValidationHandler.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/war/WarSystem.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/GuildManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/GuildUtils.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionUtils.java
- plugin/src/test/groovy/net/dzikoysk/funnyguilds/FunnyGuildsSpec.groovy
> GH-1810 Fix regions not removing

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/InfoCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/placeholders/Placeholders.java
> Fix /Info command

- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
> GH-1843 Send Tablist on join

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookUtils.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/placeholderapi/PlaceholderAPIHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/IndividualPlayerList.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerChat.java
> GH-1812 Support for PlaceholderAPI (and MVdWPlaceholderAPI) in guild chats

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/SetBaseCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Guild.java
> GH-1835 Fix guild home not saving

- plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/LocationUtils.java
> GH-1863 Support float in guild home serialization/deserialization

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/GuildValidation.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/InfoCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/GuildManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/MaterialUtils.java
> GH-1849 Fix case-sensitivity in GuildValidation

- nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/playerlist/PlayerList.java
- nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/playerlist/SkinTexture.java
- nms/v1_10R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_10R1/playerlist/V1_10R1PlayerList.java
- nms/v1_11R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_11R1/playerlist/V1_11R1PlayerList.java
- nms/v1_12R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_12R1/playerlist/V1_12R1PlayerList.java
- nms/v1_13R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_13R2/playerlist/V1_13R2PlayerList.java
- nms/v1_14R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_14R1/playerlist/V1_14R1PlayerList.java
- nms/v1_15R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_15R1/playerlist/V1_15R1PlayerList.java
- nms/v1_16R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_16R3/playerlist/V1_16R3PlayerList.java
- nms/v1_17R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_17R1/playerlist/V1_17R1PlayerList.java
- nms/v1_18R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R1/playerlist/V1_18R1PlayerList.java
- nms/v1_18R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R2/playerlist/V1_18R2PlayerList.java
- nms/v1_8R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_8R3/playerlist/V1_8R3PlayerList.java
- nms/v1_9R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_9R2/playerlist/V1_9R2PlayerList.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/ReloadRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/ConfigurationFactory.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/serdes/SkinTextureSerializer.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/IndividualPlayerList.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
> GH-1902 Support custom player heads on tablist

- plugin/src/main/java/net/dzikoysk/funnyguilds/event/SimpleEventHandler.java
> GH-1884 Send event cancel message if debug mode is enabled (Resolves #1884)

- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/MessageConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/BlockBreak.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerTeleport.java
> GH-1512 Option to disable teleportation on someone's guild region (Resolves #1512)

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/MessageConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/CreateCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard6Hook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuard7Hook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/worldguard/WorldGuardHook.java
> GH-1798 Add WorldGuard flag denying guild creation

- README.md
- build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
- updater-nightly.txt
- updater.txt
> Release 4.10.1

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
Red will always be the most visible (and eye-grabbing) color for the default TAB configuration
> Make TAB footer always predominantly red

- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/ReloadRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/IndividualPlayerList.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/TablistBroadcastHandler.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
> GH-2031 Fix CME while sending tablist (#2031)

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/CommandsConfiguration.java
> GH-2017 Niepotrzebny _ w configu dla klucza break (Resolves #2017)

- README.md
- build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
- updater-nightly.txt
- updater.txt
> Release 4.10.2

- build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/HeartConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/CreateCommand.java
> GH-2069 Możliwość ustawienia offsetu dla domyślnego home gildii (Resolves #2069)

- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/protection/ProtectionSystem.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PistonUse.java
> GH-2078 Prevent piston usage in guild heart protected region (#2078)

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/TablistBroadcastHandler.java
> GH-2031 Fix CME while broadcasting tablist (Fix #2031)

- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
> Self killing fix (Suicide patch ( ͡° ͜ʖ ͡°))

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerChat.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/UserUtils.java
> GH-2090 Support colors in chat-position placeholders (Resolves #2090)

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/prefix/IndividualPrefix.java
> GH-2086 Gracze z wrogiej gildii są pokazywani jako osoby z tej samej gildii (Fix #2086)

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/MessageConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
> GH-2060 Option to prevent rank change if both players are in the same guild or allied guilds (Resolves #2060)

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/notification/bossbar/BossBarService.java
> GH-2125 Replace HashMap with ConcurrentHashMap in BossBarService (Fix #2125)

- plugin/build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/TntProtection.java
> GH-2106 Option to disable build protection after explosion in certain situations (Resolves #2106)

- plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/Database.java
Fix for this error: https://pastebin.com/itbaeSch
> Fix JDBC URL building

- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerQuit.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/DamageCache.java
> GH-2135 Fix Anti Logout plugins support

- plugin/src/main/java/net/dzikoysk/funnyguilds/event/rank/CombatPointsChangeEvent.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerDeath.java
> GH-2132 Assists fixes (#2132)

- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerTeleport.java
- plugin/src/main/resources/plugin.yml
> GH-2190 Oddzielne uprawnienie na teleportowanie do innej gildii (Resolves #2190)

- build.gradle
- plugin/build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookManager.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/decentholograms/DecentHologramsHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/holographicdisplays/HolographicDisplaysHook.java
- plugin/src/main/resources/plugin.yml
> GH-2068 Add Decent Holograms support (Resolves #2068)

- nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/packet/PacketSuppliers.java
- nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/packet/PacketSuppliersRegistry.java
- plugin/build.gradle
- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/war/WarAttackRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/concurrency/requests/war/WarInfoRequest.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/nms/heart/GuildEntityHelper.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/nms/heart/GuildEntitySupplier.java
> GH-2215 Fix heart of the guild appearing in other world (Resolves #2215)

- plugin/src/main/java/net/dzikoysk/funnyguilds/shared/bukkit/ChatUtils.java
- plugin/src/test/kotlin/net/dzikoysk/funnyguilds/shared/bukkit/ChatUtilsTest.kt
> GH-2178 Simpler HEX format (Resolves #2178)

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/ScoreboardConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/scoreboard/nametag/IndividualNameTag.java
> GH-1726 Add {POS} placeholder to NameTag (Resolves #1726)

- nms/api/src/main/java/net/dzikoysk/funnyguilds/nms/api/message/MessageAccessor.java
- nms/v1_10R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_10R1/message/V1_10R1MessageAccessor.java
- nms/v1_11R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_11R1/message/V1_11R1MessageAccessor.java
- nms/v1_12R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_12R1/message/V1_12R1MessageAccessor.java
- nms/v1_13R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_13R2/message/V1_13R2MessageAccessor.java
- nms/v1_14R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_14R1/message/V1_14R1MessageAccessor.java
- nms/v1_15R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_15R1/message/V1_15R1MessageAccessor.java
- nms/v1_16R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_16R3/message/V1_16R3MessageAccessor.java
- nms/v1_16R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_16R3/statistics/V1_16R3StatisticsAccessor.java
- nms/v1_17R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_17R1/message/V1_17R1MessageAccessor.java
- nms/v1_17R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_17R1/statistics/V1_17R1StatisticsAccessor.java
- nms/v1_18R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R2/message/V1_18R2MessageAccessor.java
- nms/v1_18R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_18R2/statistics/V1_18R2StatisticsAccessor.java
- nms/v1_19R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R1/message/V1_19R1MessageAccessor.java
- nms/v1_19R1/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R1/statistics/V1_19R1StatisticsAccessor.java
- nms/v1_19R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R2/message/V1_19R2MessageAccessor.java
- nms/v1_19R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_19R2/statistics/V1_19R2StatisticsAccessor.java
- nms/v1_8R3/src/main/java/net/dzikoysk/funnyguilds/nms/v1_8R3/message/V1_8R3MessageAccessor.java
- nms/v1_9R2/src/main/java/net/dzikoysk/funnyguilds/nms/v1_9R2/message/V1_9R2MessageAccessor.java
We already do that for actionbar in 1.19+ so why we can't do that for other things and versions...
Also we can use default interfaces instead sharing same code across every version
> Use less NMS

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/placeholderapi/PlaceholderAPIHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/scoreboard/nametag/IndividualNameTag.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/placeholders/RankPlaceholdersService.java
> GH-2227 Recolor Nametag and fix typo (Fix #2227)

- plugin/build.gradle.kts
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/ConfigurationFactory.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/P0008_Migrate_old_heart_center_configuration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/sections/HeartConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/MoveCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/CreateCommand.java
> GH-2252 Add `GRAVITY` guild center height (Resolves #2252)

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/protection/ProtectionSystem.java
This reverts commit 4a0bb3613f605b30f924ac99c16f6b30b7c70640.
Old code worked perfectly and this commit only bugged everything. I tested every world corner and everything works perfectly ¯\\\_(ツ)_/¯ so user issue lol
> Revert "GH-2208 Fix player location checking in heart protection-system"

- plugin/src/main/java/net/dzikoysk/funnyguilds/FunnyGuilds.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/MessageConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/migration/T0002_Update_tablist_keys.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistPage.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistPageSerializer.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/FunnyGuildsCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/protection/ProtectionSystem.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/IndividualPlayerList.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/TablistBroadcastHandler.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/PlayerJoin.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/rank/placeholders/RankPlaceholdersService.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/user/BukkitUserProfile.java
List:
- Update tablist config keys - we don't need these `player-list` prefix that was needed when tablist was in plugin configuration
- Make BukkitUserProfiler#getPlayer private like planned
- Cleanup ProtectionSystem a little...
> Do some cleanup

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
In 2a1e64bfc4feefb234e6bdd9344586000c164c32 I updated keys, but forgot to update also comments...
> Fix comments in TablistConfiguration

- plugin/src/main/java/net/dzikoysk/funnyguilds/config/ConfigurationFactory.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
> Register tablist migrations and fix tablist config comments

- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/HookUtils.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/placeholderapi/PlaceholderAPIHook.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/scoreboard/nametag/IndividualNameTag.java
Fix replacing nametags papi and also resolves #2266
> GH-2266 Fix NameTags (Fix #2266)

- plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatDataModel.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/FlatPatcher.java
> Fix plugin data catalog

- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
Simple implementation of the sparse storage for regions to speed up lookups based on location, as they're being done pretty frequently (during player move etc.). 
Sparse storage uses x and z chunk position of given location packed into one 64-bit integer for the key.
For further optimization (if needed), container for regions could be replaced with Long2ObjectOpenHashMap.
There is one place in the code that should use properties of the spatial storage to speed up lookup for any regions from the location in range, but it is not being done frequently, so it could be done later.
This change was tested locally, but it should be tested thoroughly if possible, as it is the critical part of the plugin.
> GH-2300 Use sparse storage for regions to speed up lookups based on location

- plugin/src/main/java/net/dzikoysk/funnyguilds/data/database/serializer/DatabaseRegionSerializer.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/flat/seralizer/FlatRegionSerializer.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/data/util/DeserializationUtils.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/admin/MoveCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/feature/command/user/EnlargeCommand.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/Region.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/guild/RegionManager.java
> GH-2326 Fix region lookups by location and some improvements to region system

- plugin/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java
[Issue](https://github.com/FunnyGuilds/FunnyGuilds/issues/2327)
> GH-2327 Trigger `GuildRegionLeaveEvent` for ender pearls

- .github/README.md
- build.gradle.kts
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/PluginConfiguration.java
- plugin/src/main/java/net/dzikoysk/funnyguilds/config/tablist/TablistConfiguration.java
- plugin/src/main/resources/plugin.yml
- updater-nightly.txt
- updater.txt
> GH-2315 Release 4.12.0
